sudo: false
language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: PHPCBF=MySource
    - php: 5.5
      env: PHPCBF=PEAR
    - php: 5.5
      env: CUSTOM_INI=1
    - php: 5.6
      env: PHPCBF=PSR1
    - php: 7.0
      env: PHPCBF=PSR2
    - php: 7.0
      env: CUSTOM_INI=1 XMLLINT=1
      addons:
        apt:
          packages:
            - libxml2-utils
    - php: 7.1
      env: PHPCBF=Squiz
    - php: 7.2
      env: PHPCBF=Zend
    - php: nightly

  allow_failures:
    - php: nightly

before_install:
  - export XMLLINT_INDENT="    "
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

before_script:
  - if [[ $CUSTOM_INI == "1" && ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then phpenv config-add php5-testingConfig.ini; fi
  - if [[ $CUSTOM_INI == "1" ]] && [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then phpenv config-add php7-testingConfig.ini; fi

script:
  - php bin/phpcs --config-set php_path php
  - phpunit tests/AllTests.php
  - if [[ $CUSTOM_INI != "1" ]]; then php bin/phpcs --no-cache --parallel=1; fi
  - if [[ $CUSTOM_INI != "1" && $TRAVIS_PHP_VERSION != "nightly" ]]; then pear package-validate package.xml; fi
  - if [[ $CUSTOM_INI != "1" ]]; then composer validate --no-check-all --strict; fi
  - if [[ $CUSTOM_INI != "1" ]]; then php scripts/build-phar.php; fi
  - if [[ $CUSTOM_INI != "1" ]]; then php phpcs.phar; fi
  # Validate the xml ruleset files.
  # @link http://xmlsoft.org/xmllint.html
  - if [[ $XMLLINT == "1" ]]; then xmllint --noout ./src/Standards/*/ruleset.xml; fi
  # Check the code-style consistency of the xml files.
  - if [[ $XMLLINT == "1" ]]; then diff -B ./phpcs.xml.dist <(xmllint --format "./phpcs.xml.dist"); fi
  - if [[ $XMLLINT == "1" ]]; then diff -B ./src/Standards/Generic/ruleset.xml <(xmllint --format "./src/Standards/Generic/ruleset.xml"); fi
  - if [[ $XMLLINT == "1" ]]; then diff -B ./src/Standards/MySource/ruleset.xml <(xmllint --format "./src/Standards/MySource/ruleset.xml"); fi
  - if [[ $XMLLINT == "1" ]]; then diff -B ./src/Standards/PEAR/ruleset.xml <(xmllint --format "./src/Standards/PEAR/ruleset.xml"); fi
  - if [[ $XMLLINT == "1" ]]; then diff -B ./src/Standards/PSR1/ruleset.xml <(xmllint --format "./src/Standards/PSR1/ruleset.xml"); fi
  - if [[ $XMLLINT == "1" ]]; then diff -B ./src/Standards/PSR2/ruleset.xml <(xmllint --format "./src/Standards/PSR2/ruleset.xml"); fi
  - if [[ $XMLLINT == "1" ]]; then diff -B ./src/Standards/Squiz/ruleset.xml <(xmllint --format "./src/Standards/Squiz/ruleset.xml"); fi
  - if [[ $XMLLINT == "1" ]]; then diff -B ./src/Standards/Zend/ruleset.xml <(xmllint --format "./src/Standards/Zend/ruleset.xml"); fi
  # Test for fixer conflicts by running the auto-fixers of each standard over all test case files.
  # This is not an exhaustive test, but should give an early indication for typical fixer conflicts.
  # For the first run, the exit code will be 1 (= all fixable errors fixed).
  # `travis_retry` should then kick in to run the fixer again which should now return 0 (= no fixable errors found).
  - if [[ $PHPCBF ]]; then travis_retry php bin/phpcbf -p ./src/Standards/ --standard=${PHPCBF} --ignore-annotations --extensions=inc,js,css --report=summary --basepath=./src/Standards/ --no-cache --parallel=50 --ignore=/src/Standards/Squiz/Tests/PHP/HeredocUnitTest.inc,/src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.inc; fi
